command:
  - "streamlit"
  - "run"
  - "src/progression_heatmap/app.py"

env:
  - name: "PROGRESSION_HEATMAP_CONFIG"
    value: "config/prod.toml"
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql-warehouse"
  - name: "PYTHONPATH"
    value: "src"
  - name: "STREAMLIT_BROWSER_GATHER_USAGE_STATS"
    value: "false"
